[2025-04-01T18:04:31.944+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-04-01T18:04:31.969+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: run_ssis_python.execute_ssis_python manual__2025-04-01T18:02:25.595802+00:00 [queued]>
[2025-04-01T18:04:31.980+0000] {taskinstance.py:2614} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: run_ssis_python.execute_ssis_python manual__2025-04-01T18:02:25.595802+00:00 [queued]>
[2025-04-01T18:04:31.981+0000] {taskinstance.py:2867} INFO - Starting attempt 1 of 2
[2025-04-01T18:04:32.004+0000] {taskinstance.py:2890} INFO - Executing <Task(PythonOperator): execute_ssis_python> on 2025-04-01 18:02:25.595802+00:00
[2025-04-01T18:04:32.012+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=175) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-04-01T18:04:32.014+0000] {standard_task_runner.py:72} INFO - Started process 176 to run task
[2025-04-01T18:04:32.015+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'run_ssis_python', 'execute_ssis_python', 'manual__2025-04-01T18:02:25.595802+00:00', '--job-id', '158', '--raw', '--subdir', 'DAGS_FOLDER/ssis.py', '--cfg-path', '/tmp/tmph3kmzx9z']
[2025-04-01T18:04:32.017+0000] {standard_task_runner.py:105} INFO - Job 158: Subtask execute_ssis_python
[2025-04-01T18:04:32.195+0000] {task_command.py:467} INFO - Running <TaskInstance: run_ssis_python.execute_ssis_python manual__2025-04-01T18:02:25.595802+00:00 [running]> on host 44edad353d34
[2025-04-01T18:04:32.287+0000] {taskinstance.py:3134} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='run_ssis_python' AIRFLOW_CTX_TASK_ID='execute_ssis_python' AIRFLOW_CTX_EXECUTION_DATE='2025-04-01T18:02:25.595802+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-01T18:02:25.595802+00:00'
[2025-04-01T18:04:32.288+0000] {taskinstance.py:732} INFO - ::endgroup::
[2025-04-01T18:04:33.034+0000] {logging_mixin.py:190} INFO - ‚ùå Error executing SSIS package: Command '"C:\Program Files\Microsoft SQL Server\160\DTS\Binn\dtexec" /F "C:\Users\Shehab\source\repos\***\Package.dtsx"' returned non-zero exit status 127.
[2025-04-01T18:04:33.035+0000] {python.py:240} INFO - Done. Returned value was: None
[2025-04-01T18:04:33.050+0000] {taskinstance.py:341} INFO - ::group::Post task execution logs
[2025-04-01T18:04:33.050+0000] {taskinstance.py:353} INFO - Marking task as SUCCESS. dag_id=run_ssis_python, task_id=execute_ssis_python, run_id=manual__2025-04-01T18:02:25.595802+00:00, execution_date=20250401T180225, start_date=20250401T180431, end_date=20250401T180433
[2025-04-01T18:04:33.146+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 0
[2025-04-01T18:04:33.159+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
